config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :profiles
  resources :posts

  devise_for :users
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_one :profile, :through => :user

  validates :picture, :description, :presence => true

  has_attached_file :picture, :styles => { :large => "600x600", :medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :posts, :through => :user

  has_attached_file :avatar, :styles => { :large => "600x600", :medium => "300x300", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :username, :avatar, :presence => true
  validates :username, length: {
    minimum: 2,
    maximum: 15
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_profile_exists

  protected

  def check_profile_exists
    if user_signed_in? && !current_user.profile
      redirect_to new_profile_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]
  before_action :set_post, only: [:show, :destroy]
  before_action :require_auth, only: [:destroy]

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to '/', :notice => 'Post deleted successfully.' }
    end
  end

  private

  def require_auth
    if @post.user_id != current_user.id
      flash[:alert] = "You are not authorized to perform that action."
      redirect_to :back
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:description, :picture)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :check_profile_exists, :only => [:new, :create]
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    redirect_to current_user.profile
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def show
    @posts = @profile.user.posts
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profiles_path, notice: 'Profile was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profiles_path, notice: 'Profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:username, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_notices!
    return "" if !alert && !notice

    flashes = ""

    alertHtml = <<-HTML
      <div class="alert alert-danger">
        #{alert}
      </div>
    HTML

    noticeHtml = <<-HTML
      <div class="alert alert-info">
        #{notice}
      </div>
    HTML

    flashes += alertHtml if alert
    flashes += noticeHtml if notice

    html = <<-HTML
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-sm-5 col-sm-offset-3">
        #{flashes}
      </div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_conditional_nav.html.erb
<% if user_signed_in? %>
  <li class=""><%= link_to 'New Post', new_post_path %></li>
  <li class="dropdown">
    <% if current_user.profile %>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="post-creator" style="background-image: url(<%= current_user.profile.avatar(:thumb) %>)"></span>
    <%= current_user.profile.username %><span class="caret"></span></a>

    <% else %>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
    <% end %>
    <ul class="dropdown-menu">
      <li><a href="/profiles">Profile</a></li>
      <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brainstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="/"><img alt="Brand" src="/logo_brainstation.svg">braInstagram</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <%= render 'layouts/conditional_nav' %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
    </div>
  </nav>
  <div class="container">
      <%= flash_notices! %>

      <%= yield %>
  </div>



</body>
</html>

app/views/posts/_post.html.erb
<div class="well well-sm">
  <p>
    <span class="post-creator" style="background-image: url(<%= post.profile.avatar(:thumb) %>)"></span>
    <strong><%= link_to post.profile.username, post.profile %></strong>
    <span style="float: right; font-size: 8pt;"><%= time_ago_in_words(post.created_at) %> ago</span>
  </p>

  <div id="postPic" style="background-image: url(<%= post.picture.url %>)">
    <% if user_signed_in? && current_user.id == post.user_id %>
      <%= button_to "Delete", post_path(post.id), data: { confirm: "Are you sure?" }, :class =>'btn btn-danger post-destroy', method: :delete %>
    <% end %>
  </div>
  <hr />
  <p>
    <span class="post-creator" style="background-image: url(<%= post.profile.avatar(:thumb) %>)"></span>
    <strong><%= link_to post.profile.username, post.profile %></strong>
    <%= post.description %>
  </p>
</div>

app/views/posts/_smallpost.html.erb
<div class="col-md-3 col-sm-6 col-xs-12 post-sm">
  <div class=" well well-sm ">
    <p>
      <span class="post-creator" style="background-image: url(<%= post.profile.avatar(:thumb) %>)"></span>
      <strong><%= link_to post.profile.username, post.profile %></strong>
      <span style="float: right; font-size: 8pt;"><%= time_ago_in_words(post.created_at) %> ago</span>
    </p>

    <div id="postPic" style="background-image: url(<%= post.picture.url %>);" onclick="document.location.href='/posts/<%= post.id %>'">
      
    </div>
    <hr />
    <p>
      <strong><%= link_to post.user.profile.username, post.user.profile %></strong> - <%= post.description %>
    </p>
  </div>

</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel">
        <h3>New Post</h3>
        <%= form_for(@post) do |f| %>
        <% if @post.errors.count > 0 %>
          <div class="alert alert-danger">
            <% @post.errors.full_messages.each do |e| %>
            <ul>
              <li><%= e %></li>
            </ul>
            <% end %>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.text_field :description, :class => 'form-control', :placeholder => "Description" %>
        </div>
        <div class="field form-group">
          <%= f.file_field :picture %>
        </div>
        <%= f.submit "Make it!", :class => 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <%= render 'posts/post', :post => @post %>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel">
        <h3>Edit Profile</h3>
        <%= form_for(@profile) do |f| %>
        <% if @profile.errors.count > 0 %>
          <div class="alert alert-danger">
            <% @profile.errors.full_messages.each do |e| %>
            <ul>
              <li><%= e %></li>
            </ul>
            <% end %>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => 'form-control', :placeholder => "Username" %>
        </div>
        <div class="field form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar %>
        </div>
        <%= f.submit "Let's go!", :class => 'btn btn-primary' %>
        <% end %>


    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="row">
  <img src="/uploads/<%= @profile.profile_pic %>" alt="" />
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel">
        <h3>Welcome to braInstagram!</h3>
        <p>
          We're going to have to ask you a few questions.
        </p>
        <p>
          Namely: what should we call you?
        </p>
        <%= form_for(@profile) do |f| %>
        <% if @profile.errors.count > 0 %>
          <div class="alert alert-danger">
            <% @profile.errors.full_messages.each do |e| %>
            <ul>
              <li><%= e %></li>
            </ul>
            <% end %>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.text_field :username, :class => 'form-control', :placeholder => "Username" %>
        </div>
        <p>
          Lastly (and we're sorry if this is a bit creepy), but what do you look like?
        </p>
        <div class="field form-group">
          <%= f.file_field :avatar %>
        </div>
        <%= f.submit "Let's go!", :class => 'btn btn-primary' %>
        <% end %>


    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="well well-sm" style="background: url(<%= @profile.avatar.url(:large) %>); background-size: cover; min-height: 225px; min-width: 225px; background-position: center;">

    </div>
  </div>
  <div class="col-md-9">
    <div class="page-header">
      <h2><%= @profile.username %></h2>
      <h5>Member for <%= time_ago_in_words(@profile.created_at) %> - <%= @profile.posts.count %> posts</h5>
    </div>
    <% if current_user.profile.id == @profile.id %>
      <%= link_to 'Edit my Profile', edit_profile_path %>      
    <% end %>

  </div>
</div>

<div class="row">
  <% @posts.each do |p| %>
    <%= render 'posts/smallpost', :post => p %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <% @posts.each do |p| %>
    <%= render 'posts/smallpost', :post => p %>
  <% end %>
</div>